project:
  type: book
  output-dir: docs  

book:
  title: "Essays on Data Science"
  author: "Rafael C. Alvarado"
  #reader-mode: true
  page-navigation: true  
  date: "9/20/2023"
  
  chapters:
  - index.qmd
  - part: "The History of Data Science"
    chapters: 
    - chapters/01_History/00-history-abstract.qmd       # Abstract
    - chapters/01_History/00-synopsis.qmd               # Synopsis
    - chapters/01_History/01-history-introduction.qmd   # Introduction
    - chapters/01_History/02-history-1960s.qmd          # Origins
    - chapters/01_History/04-history-1990s.qmd          # Statistics Disrupted
    - chapters/01_History/05-history-2000s.qmd          # Data Science Grows
    - chapters/01_History/06-history-2008-2012.qmd      # The Sexy Science
    - chapters/01_History/07-history-disconnect.qmd     # The Disconnect
    - chapters/01_History/08-history-interpretation.qmd # Conclusion
    appendices:
    - chapters/01_History/history-method.qmd
  - part: "The 4+1 Model of Data Science"
    chapters: 
    - chapters/02_Structure/01-structure-the-model.qmd
    - chapters/02_Structure/02-structure-ds-and-ai.qmd
    - chapters/02_Structure/03-structure-remarks.qmd
    appendices:
    - chapters/02_Structure/structure-sources.qmd
  # - part: "Design"
  #   chapters: 
  #   - chapters/03_Future/ethical-models.qmd
  - references.qmd
  
page-footer:
  left: |
    Written by Rafael C. Alvarado with input from many colleagues at UVA's [School of Data Science](http://datascience.virginia.edu).
  right: |
    This book was built with <a href="https://quarto.org/">Quarto</a>.


bibliography: bib/references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: report
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex


